addons:
  apt:
    packages:
      - libboost-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-test-dev
      - libglew-dev
      - libicu-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - python-pip
      - zlib1g-dev
  homebrew:
    packages:
      - ccache
      - glew
      - sdl2
      - sdl2_image
      - sdl2_mixer
      - sdl2_ttf
    update: true

before_script:
  - >
    if [ "$TRAVIS_DIST" == "trusty" ]; then \
      export DISPLAY=:99.0 && \
      sh -e /etc/init.d/xvfb start && \
      sleep 3; \
    fi

branches:
  only:
    - master
    - travis-with-caches

install:
  - >
    if [ "$TRAVIS_OS_NAME" = osx ]; then \
      # brew doesn't add a link by default
      brew link --force gettext && \
      # icu4c cannot be forced
      export ICU_ROOT="$(brew --prefix icu4c)" && \
      # add ccache to the PATH variable
      export PATH="/usr/local/opt/ccache/libexec:$PATH"; \
    fi

jobs:
  include:
    - stage: tests
      name: "Codecheck Suite"
      script: ./.travis.sh codecheck
    - script: ./.travis.sh documentation
      name: "Documentation Test"
      language: python
      install: pip install sphinx
      

#stages:
#  - tests
#  - compile
